- .gitignore
- .travis.yml
- scripts/test.sh
- tests/docker-compose.yml
Also revert "Use travis yarn and bundle caching (#9)"
This reverts commit 3ad9c127f4c20abca898c0372faa5cdbec9099aa.
> Switch test container to containaruba

- app/docker/Dockerfile.grafana
- app/docker/configs/grafana-influxdb-datasources.yml
- app/docker/docker-compose.tools.yml
sets up sources for telegraf (the default) and the influxdb internal databases.
> Configure grafana influxdb datasoruces

- .dockerignore
- .gitignore
- CHANGELOG.md
- app/docker/Dockerfile.cyberchef
- app/docker/Dockerfile.grafana
- app/docker/Dockerfile.telegraf
- app/docker/docker-compose.tools.yml
- scripts/danger.sh
- tests/dangerfile.js
- tests/features/tools.feature
Environment variables like `$DAB_TOOLS_TELEGRAF_TAG` can now be used to select the docker tag to use for this image.
Fixes #8
> Allow tools version to be configured by env var

- CHANGELOG.md
- app/lib.sh
- tests/features/config.feature
`dab config set` and `dab config add` are now idempotent.
Fixes #22
> Make config operations idempotent

- CHANGELOG.md
- dab
> More robust UID and GID detection

- Dockerfile
- tests/features/misc.feature
Should fix truncation when built by docker hub
Relates to #106
> Use current master for changelog

- CHANGELOG.md
- app/lib/hooks.sh
Should only have a performance impact on short commands when influxdb service is running.
> Hook to add chronograf annotations for all executions

- CHANGELOG.md
- Dockerfile
- README.md
- app/bin/dab
- app/default-entrypoint.sh
- app/main.sh
- app/subcommands/group/start
- app/subcommands/group/update
- app/subcommands/pki/destroy
- app/subcommands/repo/add
- app/subcommands/repo/entrypoint/run
- app/subcommands/repo/list
- scripts/test.sh
Old command still exists but the new one is used for new entry points
> Deprecate compose-external-default-network.sh in favor of docker-compose-gen

- CHANGELOG.md
- app/lib/config.sh
- app/subcommands/config/keys
- tests/features/config.feature
- tests/features/services.feature
No parameter will give the same output but can take a config key to
scope the output
Fixes #130
> Allow limiting config key output

- CHANGELOG.md
- Dockerfile
- app/lib/hooks.sh
- dab
- scripts/test.sh
- tests/features/misc.feature
Instead make a temporary user, should allow for single sign on users.
Fixes #145
> Do not use hosts /etc/passwd when UID is not in it

- app/subcommands/services/destroy
- app/subcommands/services/start
- app/subcommands/tools/destroy
- app/subcommands/tools/start
fixes a bug where destroying a single service removes all tools
> Do not remove orphans all the time, prevents services killing tools

- app/docker/configs/docker-gen/templates/telegraf.conf.tmpl
- app/docker/configs/vault.hcl
- tests/features/services.feature
Also stop testing it in CI, dynamic config seems to make CI flakey
> Now telegraf logs are less noisy, disable its quiet switch

- app/docker/Dockerfile.remote_syslog2
- app/docker/configs/remote_syslog2.yml
- app/docker/docker-compose.deps.yml
- app/docker/docker-compose.services.yml
- completion/services.go
Adds a docker volume named dab_logs where any .log files will be
ingested from.
Fixes #123
> Add remote-syslog2 to services, can now ingest file into dab chronograf

- app/docker/Dockerfile.fn
- app/docker/docker-compose.services.yml
- app/lib/docker.sh
- app/lib/update.sh
- app/subcommands/services/address
- app/subcommands/services/update
- app/subcommands/tools/address
- app/subcommands/tools/update
- dab
- tests/features/services.feature
Fn Project is a serverless framework facilitating functions as a service.
Also Fixes up some issues with updating and displaying addresses for services and tools, tc..
> Add Fn Project to services

- app/docker/docker-compose.couchdb.yml
- app/docker/docker-compose.elasticsearch.yml
- app/docker/docker-compose.influxdb.yml
- app/docker/docker-compose.kafka.yml
- app/docker/docker-compose.memcached.yml
- app/docker/docker-compose.minio.yml
- app/docker/docker-compose.mysql.yml
- app/docker/docker-compose.postgres.yml
- app/docker/docker-compose.redis.yml
- app/subcommands/apps/explore
attaching projects to the dab_apps network is a bit gross but putting the most likely apps to directly interface with your projects on the lab network then they resolve to their compose service name by default so kafka is kafka etc.
> Explore subcommand and more apps on the lab network

- app/subcommands/pki/ready
The intermediate does not well install into some devices whereas the root does
> Install root CA via mitm.it not intermediate when using mitmproxy

- app/subcommands/pki/ready
Prevents cert errors in browsers without the user being warned why
> Do not suppress certutil errors on pki ready

- app/subcommands/update
recent changes make the DAB_AUTOUPDATE environment variables inheritable made it impossible to run `dab update` to manually ask for an update.
> 'dab update' now ignores DAB_AUTOUPDATE allowing for usage on demand

- dab
Solves a problem with `dab update` not displaying the relevant changelog when an ssh agent socket is passed into the container.
> Persist host's SSH_AUTH_SOCK path into the dab container

- app/subcommands/pki/ready
Otherwise mitmproxy cannot start as it requires both cert and key
Fixes #272
> Use CA bundle where needed for mitmproxy instead of just the cert

- app/docker/configs/docker-gen/templates/telegraf.conf.tmpl
- app/docker/docker-compose.burrow.yml
Ingests into influxdb via telegraf by default but has no dashboard afaik
> Add burrow app to monitor kafka lag

- app/lib/docker.sh
Fixes bug introduced in #278 for apps with hypenated names such as `kafka-topics-ui`
> Fix discovering dependencies for apps with hyphenated names

- app/docker/docker-compose.elasticsearch.yml
Seems to have auth off on 6.0 by default but on for 5.6 and lower
> Disable elasticsearch authentication

- app/docker/docker-compose.mitmproxy.yml
- app/lib/docker.sh
- app/lib/hindsight.sh
- app/subcommands/network/proxy
- completion/main.go
- tests/features/network.feature
Add new `dab network proxy` subcommand that asserts the pki is configured correctly for mitmproxy then starts mitmproxy and gives tips on starting to use it.
> Proxy subcommand

- app/subcommands/repo/list
- tests/features/repo.feature
Adds an extra column to the `repo  list` output that uses the repos url or a
custom url (config key: alt_url) if defined.
feature request from #265
> Add url column to repo list output

- app/docker/Dockerfile.postgres
- app/docker/docker-compose.ansible.yml
- app/docker/docker-compose.postgres.yml
Postgres can now be customized via flags (`-c` can set any config file value) and its locale can be changed with env vars (requires a `dab apps update postgres`) and starts a new config namespace for apps bind mounts to expose the provisioning directory.
- Increment of #305
- Closes #308
> Ansible env var passthrough and postgres configurability

- app/docker/docker-compose.ansible.yml
Home access is too broad and unsafe, pass through the env var and bind mount `DAB_CONF_PATH` and `DAB_REPO_PATH` instead.
- #305
> Revoke home access for ansible

- app/subcommands/group/repos
- tests/features/group.feature
Fix the `dab group repo` command to accept adding extra arguments to a
repos entrypoint.
Bug fix.
- Fixes #306
> Fix `dab group repo` to add extra entrypoint args

- app/subcommands/repo/clone
- tests/features/repo.feature
Fix `dab repo clone` to clone git submodules
Fixes the `dab repo clone` command to clone the desired repository and
any submodules of that repository.
- Fixes #313
> Fix dab not cloning git submodules

- README.md
- app/subcommands/tip
- dab
Increment to - Allow for users without docker access that use sudo to still mount their home
Increments @Nekroze's - "Allow for users without docker access that use sudo to still mount their home" commit. Specificity this pull request includes that commit and additions to the README.md and app/subcommands/tip files, to notify users that to retain any environmental variables while using `sudo`, that they should run dab with:
```bash
$ sudo -E dab --help
```
> Better sudo support increment

- completion/main.go
`dab network recreate` and its aliases are now in shell completion.
> Add network recreate and its aliases to shell completion

- .circleci/config.yml
- scripts/request-stable-update.sh
Adds a script that can request the `stable` branch be updated from the `master` branch and schedule it to run in CircleCI at midnight on Monday and Wednesday of each week.
- Implements #328
> Automated PR to stable

- app/subcommands/repo/list
- tests/features/repo.feature
Adds tests for the `repo list` subcommand that test:
- CLEAN status,
- UPTODATE status
Adds test for  `dab repo list`, that test the output of the CLEAN and UPTODATE columns.
- Increment of #230
> Add repo list clean and up to date tests

- tests/features/version.feature
Adds a test for the `dab version` command, that tests the output for the following version info:
- Dab Version
- Server Version
- Runtimes
- Kernel Version
- Operating System
- Architecture
- Increment of #230
> Test for dab version command

- Dockerfile
- app/docker/docker-compose.adminer.yml
- app/docker/docker-compose.burrow.yml
- app/docker/docker-compose.chronograf.yml
- app/docker/docker-compose.consul.yml
- app/docker/docker-compose.cyberchef.yml
- app/docker/docker-compose.gaia.yml
- app/docker/docker-compose.grafana.yml
- app/docker/docker-compose.kafka-rest.yml
- app/docker/docker-compose.kafka-topics-ui.yml
- app/docker/docker-compose.kapacitor.yml
- app/docker/docker-compose.kibana.yml
- app/docker/docker-compose.minio.yml
- app/docker/docker-compose.mitmproxy.yml
- app/docker/docker-compose.ntopng.yml
- app/docker/docker-compose.openvas.yml
- app/docker/docker-compose.pgweb.yml
- app/docker/docker-compose.portainer.yml
- app/docker/docker-compose.selenium.yml
- app/docker/docker-compose.traefik.yml
- app/docker/docker-compose.vyne.yml
- app/subcommands/apps/address
- app/subcommands/apps/start
This changes to the latest version of ishmael which displays port maps and uses it for all dockerized app user interfaces. Incidently this also fixes `dab apps` usage issues on OSX.
- Closes #351
> Make dab apps use safe port maps instead of exposures for UIs

- app/subcommands/apps/start
Fix apps start address bug introduced in #352. `dab apps address` still works.
- Fixes ad hoc bug
> Fix app start address filter

- dab
Use XDG base directory specified environment variables to construct default config and repo paths.
- Closes #364
> Support XDG base dir spec for DAB_REPO_PATH DAB_CONF_PATH defaults

- app/docker/docker-compose.sam.yml
Passes `/tmp` from host into the Sam app to try fix lambda invocation..
- Fixes #374
> Share hosts /tmp with sam app for local lambda invocation

- tests/features/apps.feature
Add a test that tests if `dab app start` starts service apps on their standard ports
- Increment of #230
> Add service app start test

- app/subcommands/repo/add
- tests/features/repo.feature
Add optional third argument to `dab repo add` to accept the tip to use for the repo.
- Increment of #380
> Allow setting tip when adding a repo

- app/bin/recklessly
- app/subcommands/repo/entrypoint/create
- app/subcommands/repo/entrypoint/list
- app/subcommands/repo/entrypoint/run
- tests/features/repo.feature
Global entrypoints are defined once and can be run on any repo if the repo does not have an entrypoint of the same name to override.
- Closes #381
> Add support for global entrypoints

- app/subcommands/repo/list
Solves an issue with invalid config items being displayed as repos, adds a small validation to `dab repo list` to remedy.
- Fixes #394
> Ensure listed repos are valid before displaying

- app/subcommands/repo/entrypoint/run
This allows global entrypoints to know what repo they were run on
without inspecting pwd.
- Relates to #381
> Set DAB_CURRENT_REPO to the current repo in entrypoints

- Dockerfile
Does what it says on the tin, should result in a smaller image that is faster to build.
> Install smaller subset of docker packages when building image

- app/subcommands/group/run
Reading repo and groups in a while loop can result in broken group
configs if any of the repo apps read from stdin and so delete all
subsequent repos or groups
> Fix group start command

- app/docker/docker-compose.mailhog.yml
- tests/features/apps.feature
SMTP email testing
- SMTP server in docker and store in memory by default. Configure dev application to use mailhog limits risk of spamming your SMTP mail infrastructure. 
- View email using docker logs
- View email using web interface
- Lightweight 19MB image
- For other benefits see https://github.com/mailhog/MailHog
> Add MailHog application

- app/subcommands/group/run
- tests/features/group.feature
Make 'dab group start' fail fast
- Closes and fixes #418
> Make 'dab group start' fail fast

- dab
This mount is a bit sketchy but the docker group id is often needed but
not necessarily known by the end user. Latest docker for mac does not
allow mounting into /etc so this must be given via env var to skip
mounting.
Also includes some tweaks to formatting and mount unix docker socket to
a consistent location within dab.
> If given DAB_DOCKER_GID do not mount /etc/group

- Dockerfile
Fixes #420 caused by recent breaking changes upstream in 1.25.0 but
should be fixed once 1.25.1 is released at which time this can and
should be reverted.
- Fixes #420
> Lock docker-compose to 1.24.x on stable branch

- Dockerfile
Fixes #420 caused by recent breaking changes upstream in 1.25.0 but
should be fixed once 1.25.1 is released at which time this can and
should be reverted.
- Increment of #420
> Lock docker-compose to 1.24.x

- app/docker/Dockerfile.ansible
Newer versions have moved to far forwards ahead of Ansible.
- Increment of #426
> Pin ansible base image for continued py-jinja2 support

- Dockerfile
This is a common hurdle to people contributing to this project. People often are asked to rebase and then never return, due to the github fork model this leaves an MR open forever that while easy to fix, no one can but the original author.
Hopefully this can loosen up the requirements so people do not have to grok rebase to contribute.
> Exclude merge commits from the changelog

- .circleci/config.yml
- .envrc
- Dockerfile
- app/docker/Dockerfile.sqliv
- app/docker/Dockerfile.xsstrike
- app/docker/docker-compose.mitmproxy.yml
- app/subcommands/pki/ready
- tests/features/config.feature
Alpine package names on their latest versions have been changed and can
now install the binary cryptography module from the package manager.
Some other changes to include pip or enforce an older alpine version
where python 2 is already specified.
Includes small test change to avoid issues with escaping inside gherkin files.
- https://app.circleci.com/pipelines/github/Nekroze/dab/1438/workflows/b7c30d5c-da55-43c7-aa4b-cb31c2119c13/jobs/3802
> Fix build issues with python 2 vs 3 name changes

- app/subcommands/repo/entrypoint/run
Allow shellcheck to specify external sources
when including scripts for var based paths.
For example:
\# shellcheck source=repo/project/files/script.sh
. "$DAB_CONF_PATH/repo/project/files/script.sh"
> Allow external sources for shellcheck

- .circleci/config.yml
- Dockerfile
- app/bin/dar-link-dest
- app/bin/maybe_update_wrapper
- app/bin/query_user
- app/docker/docker-compose.mitmproxy.yml
- app/lib/hooks.sh
- app/subcommands/repo/entrypoint/run
- dab
Add docker compose v2
* Install docker compose v2 (docker-cli-compose package)
Tests
* Had troubles with the test or feature that updates the wrapper file. With the file being docker mounted, it was not easily able to update the file in place. I've switched this to mount the containing folder instead which works well.
* Pin mitmproxy version to v6 so the health check works (it needs wget)
* Swapped to official linter images shfmt and golangci-lint rather than using a golangci-lint and installing ourselves
* Updated various shellcheck quoting issues
* Gitter webhook wasn't working so I've dropped it from circleci config
> Add Docker Compose v2

- Dockerfile
- app/docker/Dockerfile.cyberchef
- app/docker/Dockerfile.remote_syslog2
- tests/Dockerfile.tourist
Add docker-cli-buildx
DEPRECATED: The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit: https://docs.docker.com/go/buildx/
> Add docker-cli-buildx package
