- .gitignore
- .travis.yml
first step to fully replicating CI locally.
> Use travis yarn and bundle caching

- .dockerignore
- tests/docker-compose.yml
- tests/features/config.feature
- tests/features/network.feature
- tests/features/repo.feature
- tests/features/shell.feature
- tests/features/smoke.feature
- tests/features/tools.feature
Make test cases more realistic.
> Test with path

- .circleci/config.yml
- CHANGELOG.md
- README.md
- app/lib.sh
- app/subcommands/repo.sh
- tests/dangerfile.js
- tests/features/config.feature
- tests/features/repo.feature
Can group repos and tools to start or update together
Fixes #18
> Add repo groups subcommand

- CHANGELOG.md
- app/docker/Dockerfile.vault
- app/docker/configs/telegraf.conf
- app/docker/configs/vault.hcl
- app/docker/docker-compose.tools.yml
- app/subcommands/tools.sh
Implements a vault (in non dev mode, persistence provided via consul) and vaultbot container in the tools subcommand.
> Add vault and vaultbot to tools

- CHANGELOG.md
- app/subcommander.sh
- app/subcommands/config/add.sh
- app/subcommands/config/get.sh
- app/subcommands/config/set.sh
- app/subcommands/network/shell.sh
- app/subcommands/repo/add.sh
- app/subcommands/repo/clone.sh
- app/subcommands/repo/entrypoint/start.sh
- app/subcommands/repo/entrypoint/stop.sh
- app/subcommands/repo/fetch.sh
- app/subcommands/repo/group/repo.sh
- app/subcommands/repo/group/start.sh
- app/subcommands/repo/group/tool.sh
- app/subcommands/repo/group/update.sh
- app/subcommands/repo/require.sh
- app/subcommands/shell.sh
- app/subcommands/template.sh
- app/subcommands/tools.sh
- tests/features/misc.feature
- tests/features/tools.feature
Moves around tool listing but makes help and usage info for all subcommands automatically.
> Generate help for leaf subcommands

- CHANGELOG.md
- Dockerfile
- app/subcommands/completion.sh
- app/subcommands/repo/entrypoint/set/script.sh
- dab
Also remove old home passthrough
Fixes #39
> Pass DAB_USER in to dab

- .dockerignore
- scripts/danger.sh
previously unknown regression
Fixes #41
> Fix linting danger.sh

- app/docker/docker-compose.network.yml
- app/docker/docker-compose.tools.yml
> Add tmpfs to all child containers

- CHANGELOG.md
- app/main.sh
also on no subcommand
Fixes #52
> Do not ensure network via hook when running network commands

- CHANGELOG.md
- app/lib/config.sh
- app/main.sh
- app/subcommands/shell.sh
- dab
- tests/features/config.feature
environment config namespace stores kv of env vars loaded at dab start
Fixes #54
> Configurable ENV

- CHANGELOG.md
- README.md
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/lib.sh
- app/lib/services.sh
- app/lib/vault.sh
- app/subcommands/pki/destroy.sh
- app/subcommands/pki/issue.sh
- app/subcommands/pki/ready.sh
- app/subcommands/services/address.sh
- app/subcommands/services/destroy.sh
- app/subcommands/services/start.sh
- app/subcommands/tools/destroy.sh
- tests/features/misc.feature
- tests/features/network.feature
- tests/features/pki.feature
pki uses vault and vaultbot to provide easy tls issuance and renewal
Fixes #57
> Add pki subcommand namespace

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- completion/main.go
- dab
- default.nix
> Some cleanup

- completion/main.go
Replaced set with create
Fixes #63
> Update dab repo entrypoint completion

- CHANGELOG.md
- app/subcommands/pki/issue.sh
Reduce clutter left behind
Fixes #68
> Remove ephemeral vaultbot containers

- CHANGELOG.md
- Dockerfile
- app/subcommands/pki/ready.sh
Detects browser certificate databases and injects the CA
Fixes #67
> Install PKI CA in browsers

- .dockerignore
- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- Dockerfile
- app/subcommander.sh
- dab
- scripts/danger.sh
- tests/features/misc.feature
> Add --version switches

- CHANGELOG.md
- app/subcommander.sh
- app/subcommands/repo/entrypoint/create.sh
- app/subcommands/services/list.sh
- app/subcommands/tools/list.sh
Various issues touched
Related to #77
Fixes #76
> Misc fixes

- CHANGELOG.md
- Dockerfile
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/lib/compose.sh
- app/subcommands/services/list.sh
- app/subcommands/tools/list.sh
Lists for services and tools are now dynamic
Fixes #72
> Dynamic lists

- CHANGELOG.md
- README.md
- app/docker/Dockerfile.grafana
- app/docker/configs/grafana-elasticsearch-datasources.yml
- app/docker/configs/telegraf.conf
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- completion/services.go
- tests/features/services.feature
> Add elasticsearch to services

- app/docker/configs/telegraf.conf
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- completion/services.go
> Add kafka to services

- CHANGELOG.md
- app/lib/hooks.sh
- app/lib/update.sh
Actually pull the image...
Fixes #83
> Fix update subcommand and hook

- CHANGELOG.md
- app/subcommands/network/recreate.sh
grabs lab and services containers and reconnects after recreating
network
Fixes #88
> Reconnect containers on network recreate

- CHANGELOG.md
- app/subcommands/tools/start.sh
- tests/docker-compose.yml
- tests/features/config.feature
- tests/features/pki.feature
This was also effecting groups starting headless tools
Fixes #95
> Do not error out when starting headless tools

- CHANGELOG.md
- Dockerfile
- app/lib/hooks.sh
- app/lib/update.sh
- app/subcommands/completion.sh
- tests/docker-compose.yml
Can be disabled with env var
Fixes #99 
Fixes #103
> Auto update completion binary

- CHANGELOG.md
- app/lib/update.sh
- app/subcommands/repo/fetch.sh
- app/subcommands/repo/list.sh
Fetches repos and indicates if they are on origin/master.
Relates to #4
> Repo update indicator

- CHANGELOG.md
- Dockerfile
> Fix changelog

- app/lib/hooks.sh
> Use detached docker runs for annotation hook

- .circleci/config.yml
- .envrc
- CHANGELOG.md
- CONTRIBUTING.md
- completion/main.go
- scripts/build.sh
- scripts/test.sh
- tests/docker-compose.dind.yml
- tests/docker-compose.local.yml
- tests/docker-compose.yml
Run tests in dind by default but support local execution for faster dev cycles
> Local tests

- CHANGELOG.md
- app/lib/vault.sh
- scripts/test.sh
- tests/features/config.feature
- tests/features/pki.feature
- tests/features/repo.feature
should have faster CI runs with smaller container
> Support latest containaruba version

- tests/docker-compose.yml
> Use alpine tag for containaruba test image

- CHANGELOG.md
- app/lib/vault.sh
- app/subcommands/pki/ready
- tests/features/pki.feature
must use vault 0.11.4 and higher for this afaik
Fixes #121 
Fixes #87
> Newer vault initialized checks

- CHANGELOG.md
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/subcommands/pki/destroy
> Fix some issues and reduce log noise

- CHANGELOG.md
- Dockerfile
- go.mod
- go.sum
> Use go modules

- CHANGELOG.md
- Dockerfile
- app/subcommands/changelog
- scripts/test.sh
- tests/features/misc.feature
Now the newest changes are at the bottom
> Reverse the changelog subcommand output

- CHANGELOG.md
- app/docker/docker-compose.tools.yml
- app/lib.sh
- app/lib/hooks.sh
- app/lib/output.sh
- app/main.sh
- app/subcommands/template
- app/subcommands/tip
- app/subcommands/tools/list
- completion/main.go
- tests/features/misc.feature
- tests/features/services.feature
- tests/features/tools.feature
Added to hooks and reordered some hooks
Fixes #129
> Add hourly tips to help discover and learn subcommands

- .circleci/config.yml
- CHANGELOG.md
- app/lib/hooks.sh
- app/lib/services.sh
- app/lib/tools.sh
- app/subcommands/services/address
- app/subcommands/services/update
- app/subcommands/tools/address
- app/subcommands/tools/update
- completion/main.go
- tests/features/group.feature
- tests/features/services.feature
- tests/features/tools.feature
Missed goimports formatting completion
> Support docker-compose 1.23.0

- app/docker/docker-compose.deps.yml
- app/docker/docker-compose.lab.yml
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/lib/config.sh
- app/lib/docker.sh
- app/lib/vault.sh
- app/subcommands/services/destroy
- app/subcommands/tools/destroy
- app/subcommands/tools/list
- tests/features/group.feature
- tests/features/services.feature
- tests/features/tools.feature
All containers now use the `dab_` prefix and no suffix for predictable names.
> Simpler container names and misc cleanup and fixes

- .github/ISSUE_TEMPLATE/change_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Dockerfile
- README.md
> Add multitail to dab image

- .circleci/config.yml
- app/lib/dab.sh
- dab
- tests/docker-compose.yml
- tests/features/config.feature
Should resolve issues blocking users
Fixes #163
> Always run dab with a tty for tools

- app/docker/docker-compose.services.yml
- app/subcommands/group/start
Remove redundant update checks and mandatory vault metrics.
> Performance increases

- app/docker/docker-compose.deps.yml
- app/docker/docker-compose.persist.yml
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/lib/hooks.sh
- app/subcommands/network/recreate
- app/subcommands/network/shell
Moves all dep links to a single file and makes dab_logs always exist
> Refactor docler compose files, logs volume now persists

- Dockerfile
- app/lib/docker.sh
- app/subcommands/services/config
- app/subcommands/tools/config
- tests/features/services.feature
- tests/features/tools.feature
Should be useful for planning service and tool usage.
Fixes #171
> Add config subcommand to tools and services

- .circleci/config.yml
- app/docker/Dockerfile.ansible
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/subcommands/tip
- completion/main.go
- completion/tools.go
- dab
- scripts/tagged_tests.sh
- scripts/test.sh
- tests/features/config.feature
- tests/features/group.feature
- tests/features/misc.feature
- tests/features/network.feature
- tests/features/repo.feature
- tests/features/services.feature
- tests/features/shell.feature
- tests/features/tools.feature
and some test cleanup and tagging plus a move of watchtower to services where it belongs
> Add ansible to tools

- app/docker/Dockerfile.xsstrike
- app/docker/docker-compose.tools.yml
- completion/tools.go
- tests/features/tools.feature
XSStrike allows automated XSS vulnerability detection
Fixes #175
> Add XSStrike to tools

- .github/ISSUE_TEMPLATE/change_request.md
- Dockerfile
- app/docker/docker-compose.services.yml
- app/docker/docker-compose.tools.yml
- app/lib/docker.sh
- app/lib/hooks.sh
- app/subcommands/pki/issue
- app/subcommands/pki/ready
- app/subcommands/repo/entrypoint/run
- app/subcommands/services/address
- app/subcommands/services/restart
- app/subcommands/services/start
- app/subcommands/tip
- app/subcommands/tools/address
- app/subcommands/tools/restart
- app/subcommands/tools/start
- tests/features/group.feature
- tests/features/tools.feature
Replace shell functions with ishmael
Fixes #176
> Utilize ishmael

- Dockerfile
- app/default-entrypoint.sh
- dab
Added example usage to default entrypoint script as well.
Fixes #179
> Add kubectl and use host network for kubernetes integration

- app/docker/docker-compose.apps.yml
- app/subcommands/repo/entrypoint/run
- app/subcommands/tip
- completion/apps.go
> openwhisk dependencies

- .circleci/config.yml
- Dockerfile
- app/bin/dab
- app/lib/docker.sh
- app/lib/hooks.sh
- app/lib/output.sh
- app/lib/update.sh
- app/subcommands/repo/entrypoint/run
- app/subcommands/tip
- dab
- tests/features/group.feature
- tests/features/misc.feature
> Add DAB_DEBUG & DAB_PROFILING env var handling

- app/docker/docker-compose.mitmproxy.yml
- app/subcommands/apps/exec
- app/subcommands/repo/entrypoint/run
- completion/apps.go
- dab
- tests/features/apps.feature
- tests/features/group.feature
> MITMproxy and misc

- app/subcommands/repo/list
Makes the ticks green and the crosses red.
Fixes #236
> Colorize the UPTODATE column of dab repo list output

- app/lib/hooks.sh
- app/lib/update.sh
- app/subcommands/tip
- dab
- tests/docker-compose.local.yml
- tests/docker-compose.yml
Instead of using yes or no for some.
Fixes #234
> All boolean env vars now take true or false

- Dockerfile
found I could do this and it keeps the dockerfile simple
> Slightly simpler Dockerfile and docker image

- app/docker/docker-compose.kafka-rest.yml
- app/docker/docker-compose.kafka-topics-ui.yml
- app/docker/docker-compose.kafkacat.yml
Affects apps; kafka-rest, kafka-topics-ui, and kafkacat.
Fixes #242
> Env vars to configure which kafka and zookeeper apps connect to

- app/docker/configs/docker-gen/templates/telegraf.conf.tmpl
- app/lib/update.sh
- app/subcommands/apps/destroy
- app/subcommands/pki/destroy
- app/subcommands/repo/clone
- dab
- tests/features/repo.feature
telegraf now checks ping to github.com and 1.1.1.1 as well
simpler destruction of apps and vaults
repos with uncommitted changes are not up to date any more
> Misc changes

- app/lib/output.sh
- app/lib/update.sh
- app/subcommands/pki/destroy
some tweaks to the error handling and messaging around wrapper update failures.
> Safer wrapper update

- app/lib/update.sh
- app/subcommands/repo/list
- dab
> Issues 249, 250, and 251

- app/lib/update.sh
- dab
- tests/docker-compose.local.yml
- tests/docker-compose.yml
- tests/features/misc.feature
> Support non /home home directories 

- .circleci/config.yml
- README.md
- scripts/ux-test.sh
https://nekroze.github.io/DabUX/
> Run Dab UX regression tests on each version

- Dockerfile
- app/docker/docker-compose.telegraf.yml
- app/docker/docker-compose.traefik.yml
simple version bump for better support of docker-compose replicas
> Update ishmael to v1.2.2

- README.md
- app/lib/hindsight.sh
- app/subcommands/pki/issue
- app/subcommands/pki/ready
> Cfssl cleanup

- .circleci/config.yml
- scripts/test.sh
- tests/docker-compose.yml
Circle CI can ingest the output to give test summaries
> Ingest test summaries

- CONTRIBUTING.md
- scripts/test.sh
> default to local runtime for tests

- completion/apps.go
> Add burrow to apps shell completion

- .circleci/config.yml
- Dockerfile
- app/lib/docker.sh
More stable interface and no need to pipe yq to jq.
> Switch to the correct yq for jq compatibility

- .circleci/config.yml
- README.md
The stable stream is intended to be merged to periodically
> Announce the stable updates stream

- .circleci/config.yml
- Dockerfile
Postgres client pulled from alpine image.
Fixes #291
> Add psql binary to dab image

- .circleci/config.yml
- Dockerfile
- README.md
This is a merge to `stable` testing #285
> Stable stream merge test

- .github/CODE_OF_CONDUCT.md
- .github/pull_request_template.md
Code of conduct and pull request template increments on #299
> Increment on community documentation

- app/lib/config.sh
- tests/features/config.feature
> Allow envvar substiution in files config files 

- app/subcommands/tip
- tests/features/misc.feature
Increased test coverage for tips
Increments towards #230
> Add DAB_TIPS_BUILTIN variable to disable built in tips

- app/subcommands/repo/clone
- tests/features/repo.feature
Implements repo remote configurations.
- Closes #296
> Support repo remote configurations

- .github/pull_request_template.md
- CONTRIBUTING.md
- app/lib/update.sh
Describe the changes and any reasoning behind them that is relevant here.
- Increment of #299
> Community structure section in CONTRIBUTING

- app/docker/Dockerfile.ansible
- app/docker/docker-compose.ansible.yml
Use docker gid for ansible user and mount docker.sock for the docker module.
- Closes #305
> Ansible docker support

- app/docker/Dockerfile.ansible
- app/docker/docker-compose.ansible.yml
Ansible broke by #307 not using the testing repo for docker-compose install.
- Increment of #305
> Fix ansible docker-compose install and run as default user

- README.md
- app/lib/hindsight.sh
- app/subcommands/tip
Describe the changes and any reasoning behind them that is relevant here.
- Increment of #299
- Closes #287
> Announcing more maintainers and gitter

- .circleci/config.yml
- app/docker/Dockerfile.postgres
Fixes a bug introduced in #310 breaking postgres start and notify gitter of CI builds.
- Increment of #308
> Postgres locale fix

- CONTRIBUTING.md
Add section on design and maintainer decisions.
- Closes #299
> Improve CONTRIBUTING docs

- app/docker/docker-compose.selenium.yml
Describe the changes and any reasoning behind them that is relevant here.
- Increment of #
- Closes #
- Fixes #
> Add DAB_APPS_SELENIUM_TZ Passthrough to Selenium App

- scripts/request-stable-update.sh
- tests/dangerfile.js
PR should no longer fail danger checks.
- Increment of #328
> Add description to stable update pr script

- .circleci/config.yml
- .dockerignore
- Dockerfile
- README.md
- app/docker/docker-compose.selenium.yml
- app/lib/hooks.sh
- app/lib/update.sh
- app/subcommands/completion
- app/subcommands/repo/list
- dab
- scripts/request-stable-update.sh
- tests/dangerfile.js
- tests/features/misc.feature
- tests/features/repo.feature
- tests/features/version.feature
Pull patches from master over to stable.
> Update Stable Branch

- app/docker/docker-compose.grafana.yml
- tests/dangerfile.js
Expose the grafana provisioning dir and more automated code review.
- Increment of #323 
- Closes #281
> Grafana provisioning

- app/docker/docker-compose.terraform.yml
- app/lib/config.sh
- app/lib/output.sh
- app/subcommands/repo/check
- app/subcommands/repo/entrypoint/run
- app/subcommands/repo/list
- app/subcommands/repo/report
- tests/features/repo.feature
When you have many repos it can get out of hand.
- Closes #319
> dab repo report

- app/bin/aws
- app/bin/sam
- app/docker/Dockerfile.sam
- app/docker/docker-compose.aws.yml
- app/docker/docker-compose.sam.yml
Add AWS and SAM command line interfaces for AWS integration and lambda testing.
> Add AWS and SAM cli tools to apps

- Dockerfile
- app/lib/config.sh
- app/lib/update.sh
Closes several new issues.
- Closes #373 
- Closes #372 
- Fixes #359 (next build will get fix from upstream)
> Bash n stuff

- app/subcommands/repo/clone
- tests/features/repo.feature
Clones now abide new tip config key.
- Closes #378
> If repo has a tip config key, check it out after clone.

- app/docker/docker-compose.kubernetes.yml
- app/lib/hooks.sh
- app/subcommands/apps/start
Add a kubernetes app using k3s.
- Closes #337
> Add kubernetes to apps

- .circleci/config.yml
- scripts/build.sh
- scripts/test.sh
Just makes editing tests so much nicer.
> Faster local testing cycles by not rebuilding in the same script

- README.md
- tests/dangerfile.js
Document customization points.
- Closes #379
- Increment of #323
> Document tweakables

- .circleci/config.yml
- Dockerfile
- app/docker/docker-compose.kubernetes.yml
> Update kubernetes k3s

- app/docker/Dockerfile.cartography
- app/docker/docker-compose.cartography.yml
- app/docker/docker-compose.neo4j.yml
Add apps `cartography` and `neo4j`.
> Add cartography and neo4j to apps

- app/docker/docker-compose.kubernetes.yml
- app/docker/docker-compose.selenium.yml
Ensures a default storage class is provisioned with the kubernetes cluster soon after it starts.
- Closes #382
> Preconfigure a kubernetes storage class

- app/docker/Dockerfile.ansible
Fix install of docker-compose in the ansible app image.
> Fix ansible app docker-compose

- .editorconfig
- app/subcommands/repo/import
- tests/features/repo.feature
Adds a new command `dab repo import` that can create config for repos already in the `$DAB_REPO_PATH`.
> Repo import

- app/subcommands/repo/import
> Remove left over debug command in repo import

- app/docker/docker-compose.kafkaview.yml
A full-featured web-based Apache Kafka consumer
- https://hub.docker.com/r/sourcelaborg/kafka-webview
- https://github.com/SourceLabOrg/kafka-webview
> Added kafkaview App

- tests/features/version.feature
Fixes consistent CI only test failures as seen in #426
> Split version smoke test to prevent CI flake

- app/docker/docker-compose.pgadmin.yml
- tests/features/apps.feature
> Added pgadmin app

- app/docker/docker-compose.kafkaview.yml
Expose Kafkaview web ui port
- Increment of #408
> Expose Kafkaview web ui port
